version: '3.9'

services:
  app:
    build: .
    container_name: oshikatu_ap
    ports:
      - "3002:3000"
    volumes:
      - ./src:/usr/src/src           # ソースコードだけマウント
      - ./public:/usr/src/public     # public をマウント
      - ./.env:/usr/src/.env         # 環境変数
      - ./package.json:/usr/src/package.json
      - ./tsconfig.json:/usr/src/tsconfig.json
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: oshikatu_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: oshikatu
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  mysql_data:
